name=RockBLOCK-9603N
version=0.1.21
author=Ground Control
maintainer=help@groundcontrol.com
sentence=RockBLOCK 9603N SBD communication library.
paragraph=This library provides simple helpers for the RockBLOCK 9603N using the Iridium SBD protocol.
url=https://github.com/rock7/RockBLOCK-9703N
category=Communication
architectures=*
